version: '3'

services:
  gateway:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: ['lith', 'app']
    command: [nginx-debug, '-g', 'daemon off;']

  lith-admin:
    image: lith
    volumes:
      - ./db:/db:rw
      - type: bind
        source: ./lith.conf
        target: /etc/lith.conf
        read_only: true
    command: [
      '-conf', '/etc/lith.conf', 'useradd',
        '-email', 'admin@example.com',
        '-password', 'admin',
        '-allow-insecure',
        '-groups', '1,2',
    ]

  lith:
    image: lith
    depends_on: ['mailhog', 'lith-admin']
    volumes:
      - ./db:/db:rw
      - type: bind
        source: ./lith.conf
        target: /etc/lith.conf
        read_only: true
    command: ['-conf', '/etc/lith.conf', 'serve']

  app:
    build:
      context: app
      dockerfile: Dockerfile

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
