version: '3'

services:
  app:
    build:
      context: app/
      dockerfile: Dockerfile
    environment:
      - API_URL=http://lith:8001
      - UI_URL=http://lith:8002
      - PREFIX=/accounts/
      - LISTEN=0.0.0.0:8000
    ports:
      - 8000:8000

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  lith-admin:
    image: lith
    volumes:
      - ./db:/db:rw
      - type: bind
        source: ./lith.conf
        target: /etc/lith.conf
        read_only: true
    command: [
      '-conf', '/etc/lith.conf', 'useradd',
        '-email', 'admin@example.com',
        '-password', 'admin',
        '-allow-insecure',
        '-groups', '1,2',
    ]

  lith:
    image: lith
    depends_on: ['mailhog', 'lith-admin']
    ports:
      # Expose only the admin panel.
      - 8003:8003
    volumes:
      - ./db:/db:rw
      - type: bind
        source: ./lith.conf
        target: /etc/lith.conf
        read_only: true
    command: ['-conf', '/etc/lith.conf', 'serve']
