package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/BurntSushi/toml"
	"github.com/husio/lith/app/lith"
)

func cmdPrintConfig(ctx context.Context, conf lith.Configuration, args []string) error {
	fl := flag.NewFlagSet("print-config", flag.ContinueOnError)
	if err := fl.Parse(args); err != nil {
		return fmt.Errorf("flag parse: %w", err)
	}

	var b bytes.Buffer

	io.WriteString(&b, `# Generated by lith print-config
#
# See https://godocs.io/github.com/husio/lith/pkg/lith#Configuration
# for a detailed configuration description.

`)

	if err := toml.NewEncoder(&b).Encode(conf); err != nil {
		fmt.Fprintf(os.Stderr, "Encode TOML configuration failed: %s\n", err)
		os.Exit(2)
	}
	_, _ = b.WriteTo(os.Stdout)

	return nil
}
