name: Build and publish documentation

on:
  push:

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: totaldebug/action-sphinx@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        sphinx_src: 'docs/source'
